"use client";

import { useState, useEffect, useRef } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import {
  Trophy, Crown, Star, Crosshair, Flame, Award,
  Download, Share2, Twitter, Copy, Check, Users,
  Play, Zap, TrendingUp, Target, FileText
} from "lucide-react";

export default function TournamentReportPage() {
  const params = useParams();
  const reportRef = useRef<HTMLDivElement>(null);
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [copiedShare, setCopiedShare] = useState(false);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    (async () => {
      const slug = params?.slug as string;
      if (!slug) return;

      // First get tournament ID from slug
      try {
        const tRes = await fetch(`/api/tournaments/${slug}`);
        if (!tRes.ok) { setLoading(false); return; }
        const tData = await tRes.json();
        if (!tData.tournament) { setLoading(false); return; }

        const reportRes = await fetch(`/api/tournaments/${tData.tournament.id}/report`);
        if (reportRes.ok) setData(await reportRes.json());
      } catch {}
      setLoading(false);
    })();
  }, [params?.slug]);

  const exportPNG = async () => {
    if (!reportRef.current) return;
    setExporting(true);
    try {
      const { toPng } = await import("html-to-image");
      const url = await toPng(reportRef.current, { backgroundColor: "#0a0a0f", quality: 1, pixelRatio: 2 });
      const link = document.createElement("a");
      link.download = `${data?.tournament?.name || "tournament"}-report.png`;
      link.href = url;
      link.click();
    } catch { alert("Export failed"); }
    setExporting(false);
  };

  const exportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      doc.setFillColor(10, 10, 15);
      doc.rect(0, 0, 210, 297, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text(data.tournament.name, 105, 25, { align: "center" });

      doc.setFontSize(10);
      doc.setTextColor(150, 150, 170);
      doc.text("TOURNAMENT REPORT", 105, 33, { align: "center" });

      // Champion
      doc.setTextColor(250, 204, 21);
      doc.setFontSize(16);
      doc.text(`CHAMPION: ${data.awards.champion?.name || "TBD"}`, 105, 50, { align: "center" });

      // Stats
      doc.setTextColor(200, 200, 220);
      doc.setFontSize(10);
      const stats = [
        `Teams: ${data.statistics.totalTeams}`,
        `Matches: ${data.statistics.completedMatches}`,
        `Total Kills: ${data.statistics.totalKills}`,
        `Total WWCDs: ${data.statistics.totalWWCDs}`,
      ];
      stats.forEach((s, i) => doc.text(s, 20, 65 + i * 7));

      // Standings
      doc.setTextColor(100, 150, 255);
      doc.setFontSize(12);
      doc.text("FINAL STANDINGS", 20, 100);

      doc.setFontSize(8);
      doc.setTextColor(200, 200, 220);
      data.standings.slice(0, 20).forEach((t: any, i: number) => {
        const y = 110 + i * 6;
        const isTop3 = i < 3;
        if (isTop3) doc.setTextColor(250, 204, 21);
        else doc.setTextColor(200, 200, 220);
        doc.text(`#${t.rank} ${t.name}  ${t.points}pts (${t.kills}K, ${t.wwcds}W)`, 20, y);
      });

      // Footer
      doc.setTextColor(80, 80, 100);
      doc.setFontSize(7);
      doc.text(`Generated by TournaOps  tournaops.com  ${new Date().toLocaleDateString()}`, 105, 290, { align: "center" });

      doc.save(`${data.tournament.name}-report.pdf`);
    } catch { alert("PDF failed"); }
    setExporting(false);
  };

  if (loading) return (
    <div className="min-h-screen bg-[#0a0a0f] flex items-center justify-center">
      <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
    </div>
  );

  if (!data) return (
    <div className="min-h-screen bg-[#0a0a0f] flex items-center justify-center text-center px-4">
      <div>
        <Trophy className="w-12 h-12 text-gray-700 mx-auto mb-4" />
        <h1 className="text-white text-2xl font-bold mb-2">Report Not Available</h1>
        <Link href="/" className="btn-primary px-6 py-2.5">TournaOps</Link>
      </div>
    </div>
  );

  const { tournament: t, standings, awards, statistics: stats, stageJourneys, stages, aiSummary } = data;
  const publicUrl = typeof window !== "undefined" ? window.location.href : "";

  return (
    <div className="min-h-screen bg-[#0a0a0f]">
      {/* Nav */}
      <div className="border-b border-white/8 bg-[#0a0a0f]/80 backdrop-blur-xl sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg overflow-hidden bg-gradient-to-br from-blue-500 to-purple-600">
              <img src="/logo.png" alt="" className="w-full h-full object-cover" />
            </div>
            <span className="text-blue-400 font-bold text-sm">TournaOps</span>
          </Link>
          <div className="flex gap-2">
            <button onClick={exportPNG} disabled={exporting} className="btn-secondary flex items-center gap-1.5 px-3 py-1.5 text-xs">
              <Download className="w-3 h-3" />PNG
            </button>
            <button onClick={exportPDF} disabled={exporting} className="btn-secondary flex items-center gap-1.5 px-3 py-1.5 text-xs">
              <FileText className="w-3 h-3" />PDF
            </button>
            <button onClick={() => { navigator.clipboard.writeText(publicUrl); setCopiedShare(true); setTimeout(() => setCopiedShare(false), 2000); }}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs ${copiedShare ? "bg-green-500/20 border-green-500/30 text-green-400" : "bg-white/5 border-white/10 text-gray-400"}`}>
              {copiedShare ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}Share
            </button>
          </div>
        </div>
      </div>

      <div ref={reportRef} className="max-w-6xl mx-auto px-4 py-8 space-y-8">

        {/*  HEADER  */}
        <div className="text-center">
          <div className="text-xs font-bold text-blue-400 uppercase tracking-[0.3em] mb-2">Tournament Report</div>
          <h1 className="text-5xl font-black text-white mb-3">{t.name}</h1>
          <div className="flex flex-wrap justify-center gap-4 text-sm text-gray-400">
            <span>Organized by <strong className="text-white">{t.organizer}</strong></span>
            <span>{stats.totalTeams} Teams</span>
            <span>{stats.completedMatches} Matches</span>
            {t.prizePool && <span className="text-yellow-400 font-bold">{t.prizePool}</span>}
          </div>
        </div>

        {/*  CHAMPION SHOWCASE  */}
        {awards.champion && (
          <div className="glass-card rounded-3xl p-8 border-2 border-yellow-500/40 bg-gradient-to-br from-yellow-500/10 via-orange-500/5 to-transparent text-center relative overflow-hidden">
            <div className="absolute -top-20 -right-20 w-64 h-64 bg-yellow-500/15 rounded-full blur-3xl" />
            <div className="relative">
              <div className="text-xs font-black text-yellow-400 uppercase tracking-[0.4em] mb-3"> Tournament Champion </div>
              {awards.champion.logo && <img src={awards.champion.logo} alt="" className="w-24 h-24 rounded-2xl mx-auto mb-3 shadow-2xl" />}
              <div className="text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-yellow-300 to-orange-400">{awards.champion.name}</div>
              <div className="grid grid-cols-3 gap-4 mt-6 max-w-md mx-auto">
                <div><div className="text-3xl font-black text-yellow-400">{awards.champion.points}</div><div className="text-xs text-gray-500">Points</div></div>
                <div><div className="text-3xl font-black text-orange-400">{awards.champion.kills}</div><div className="text-xs text-gray-500">Kills</div></div>
                <div><div className="text-3xl font-black text-red-400">{awards.champion.wwcds}</div><div className="text-xs text-gray-500">WWCD</div></div>
              </div>
            </div>
          </div>
        )}

        {/*  AI SUMMARY  */}
        {aiSummary && (
          <div className="glass-card rounded-xl p-6 border border-purple-500/20 bg-gradient-to-br from-purple-500/5 to-blue-500/5">
            <div className="flex items-center gap-2 mb-3">
              <Zap className="w-4 h-4 text-purple-400" />
              <span className="text-xs font-bold text-purple-400 uppercase tracking-wider">AI Tournament Summary</span>
            </div>
            <p className="text-gray-300 text-sm leading-relaxed italic">"{aiSummary}"</p>
            <p className="text-gray-600 text-[10px] mt-2">Generated from verified tournament data only</p>
          </div>
        )}

        {/*  PODIUM  */}
        {standings.length >= 3 && (
          <div className="grid grid-cols-3 gap-3">
            {[1, 0, 2].map(idx => {
              const t = standings[idx];
              if (!t) return null;
              const medals = ["", "", ""];
              const colors = ["text-yellow-400", "text-gray-300", "text-amber-600"];
              return (
                <div key={t.id} className={`glass-card rounded-xl p-5 text-center border ${t.rank === 1 ? "border-yellow-500/30 -translate-y-2" : "border-white/10"}`}>
                  <div className="text-4xl mb-2">{medals[t.rank - 1]}</div>
                  <div className={`text-lg font-black ${colors[t.rank - 1]}`}>{t.name}</div>
                  <div className="text-gray-500 text-xs mt-1">{t.wwcds}W  {t.kills}K</div>
                  <div className={`text-3xl font-black ${colors[t.rank - 1]} mt-1`}>{t.points}</div>
                </div>
              );
            })}
          </div>
        )}

        {/*  STATISTICS  */}
        <div>
          <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-blue-400" />Tournament Statistics
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
            {[
              { label: "Teams", value: stats.totalTeams, icon: Users, color: "text-blue-400" },
              { label: "Matches", value: stats.completedMatches, icon: Play, color: "text-green-400" },
              { label: "Total Kills", value: stats.totalKills.toLocaleString(), icon: Crosshair, color: "text-red-400" },
              { label: "Total WWCD", value: stats.totalWWCDs, icon: Crown, color: "text-yellow-400" },
              { label: "Avg Kills/Match", value: stats.avgKillsPerMatch, icon: Target, color: "text-orange-400" },
              { label: "Total Damage", value: (stats.totalDamage / 1000).toFixed(0) + "K", icon: Flame, color: "text-purple-400" },
            ].map(s => {
              const Icon = s.icon;
              return (
                <div key={s.label} className="glass-card rounded-xl p-4 border border-white/8 text-center">
                  <Icon className={`w-5 h-5 ${s.color} mx-auto mb-2`} />
                  <div className="text-2xl font-black text-white">{s.value}</div>
                  <div className="text-xs text-gray-500 mt-0.5">{s.label}</div>
                </div>
              );
            })}
          </div>
        </div>

        {/*  AWARDS  */}
        <div>
          <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
            <Award className="w-5 h-5 text-yellow-400" />Awards
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {[
              { title: " Champion", name: awards.champion?.name, stat: `${awards.champion?.points || 0} pts`, color: "border-yellow-500/30 bg-yellow-500/5" },
              { title: " Top Fragger (MVP)", name: awards.topFragger?.name, stat: `${awards.topFragger?.kills || 0} kills`, sub: awards.topFragger?.team, color: "border-red-500/30 bg-red-500/5" },
              { title: " Most Damage", name: awards.topDamage?.name, stat: `${(awards.topDamage?.damage || 0).toLocaleString()} dmg`, sub: awards.topDamage?.team, color: "border-purple-500/30 bg-purple-500/5" },
              { title: " Most WWCD", name: awards.mostWWCD?.name, stat: `${awards.mostWWCD?.wwcds || 0} wins`, color: "border-orange-500/30 bg-orange-500/5" },
              { title: " Most Consistent", name: awards.mostConsistent?.name, stat: `${awards.mostConsistent?.points || 0} pts`, color: "border-blue-500/30 bg-blue-500/5" },
              { title: " Biggest Comeback", name: awards.biggestComeback?.name, stat: `${awards.biggestComeback?.points || 0} pts`, color: "border-green-500/30 bg-green-500/5" },
            ].filter(a => a.name).map(award => (
              <div key={award.title} className={`glass-card rounded-xl p-4 border ${award.color}`}>
                <div className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">{award.title}</div>
                <div className="text-white font-bold text-lg">{award.name}</div>
                {award.sub && <div className="text-gray-500 text-xs">{award.sub}</div>}
                <div className="text-blue-400 font-mono font-bold mt-1">{award.stat}</div>
              </div>
            ))}
          </div>
        </div>

        {/*  STAGE JOURNEY  */}
        {stages.length > 0 && standings.slice(0, 5).some((t: any) => stageJourneys[t.id]?.length > 0) && (
          <div>
            <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
              <Star className="w-5 h-5 text-purple-400" />Stage Journey (Top 5)
            </h2>
            <div className="space-y-3">
              {standings.slice(0, 5).map((team: any) => {
                const journey = stageJourneys[team.id] || [];
                if (journey.length === 0) return null;
                const medals = ["", "", ""];
                return (
                  <div key={team.id} className={`glass-card rounded-xl p-4 border ${team.rank <= 3 ? "border-yellow-500/20 bg-yellow-500/3" : "border-white/10"}`}>
                    <div className="flex items-center gap-3 mb-3">
                      <span className="text-xl">{team.rank <= 3 ? medals[team.rank - 1] : `#${team.rank}`}</span>
                      <span className="text-white font-bold text-lg">{team.name}</span>
                    </div>
                    <div className="flex items-center gap-2 flex-wrap">
                      {journey.map((stage: any, idx: number) => {
                        const icons: Record<string, string> = {
                          OPEN_QUALIFIER: "", CLOSED_QUALIFIER: "", GROUP_STAGE: "",
                          SEMI_FINAL: "", GRAND_FINAL: "",
                        };
                        const statusColors: Record<string, string> = {
                          QUALIFIED: "text-green-400 bg-green-500/10 border-green-500/20",
                          ELIMINATED: "text-red-400 bg-red-500/10 border-red-500/20",
                          WILDCARD: "text-purple-400 bg-purple-500/10 border-purple-500/20",
                        };
                        return (
                          <div key={idx} className="flex items-center gap-1.5">
                            <div className={`px-3 py-1.5 rounded-lg border text-xs font-bold ${statusColors[stage.status] || "text-gray-400 bg-gray-500/10 border-gray-500/20"}`}>
                              {icons[stage.stageType] || ""} {stage.stageName} #{stage.position}
                            </div>
                            {idx < journey.length - 1 && <span className="text-gray-600"></span>}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/*  FULL STANDINGS  */}
        <div>
          <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
            <Trophy className="w-5 h-5 text-yellow-400" />Final Standings
          </h2>
          <div className="glass-card rounded-xl border border-white/10 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-white/10 bg-white/5">
                    <th className="text-left py-3 px-4 text-gray-500 text-xs uppercase">Rank</th>
                    <th className="text-left py-3 px-4 text-gray-500 text-xs uppercase">Team</th>
                    <th className="text-center py-3 px-2 text-yellow-500 text-xs uppercase">WWCD</th>
                    <th className="text-center py-3 px-2 text-orange-400 text-xs uppercase">Kills</th>
                    <th className="text-center py-3 px-2 text-blue-400 text-xs uppercase">Place</th>
                    <th className="text-center py-3 px-2 text-green-400 text-xs uppercase">Kill Pts</th>
                    <th className="text-center py-3 px-4 text-white text-xs uppercase font-bold">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {standings.map((t: any) => (
                    <tr key={t.id} className={`border-b border-white/5 hover:bg-white/3 ${t.rank === 1 ? "bg-yellow-500/5" : ""}`}>
                      <td className="py-2.5 px-4">
                        <span className={`font-mono font-black ${
                          t.rank === 1 ? "text-yellow-400" : t.rank === 2 ? "text-gray-300" : t.rank === 3 ? "text-amber-600" : "text-gray-500"
                        }`}>
                          {t.rank <= 3 ? ["","",""][t.rank-1] : `#${t.rank}`}
                        </span>
                      </td>
                      <td className="py-2.5 px-4 text-white font-semibold">{t.name}</td>
                      <td className="py-2.5 px-2 text-center"><span className={`font-bold ${t.wwcds > 0 ? "text-yellow-400" : "text-gray-700"}`}>{t.wwcds}</span></td>
                      <td className="py-2.5 px-2 text-center text-orange-400 font-mono font-bold">{t.kills}</td>
                      <td className="py-2.5 px-2 text-center text-blue-300 font-mono">{t.placementPts}</td>
                      <td className="py-2.5 px-2 text-center text-green-400 font-mono">{t.killPts}</td>
                      <td className="py-2.5 px-4 text-center"><span className={`font-mono font-black text-lg ${t.rank <= 3 ? "text-yellow-400" : "text-white"}`}>{t.points}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center pt-8 border-t border-white/10">
          <p className="text-gray-600 text-xs font-mono">
            Generated by TournaOps  tournaops.com  {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
}