"use client";

import { useRef, useState } from "react";
import { Download, FileText, X, Trophy } from "lucide-react";
import { Tournament } from "@/types/tournament";
import { getLeaderboard, getTopPlayers } from "@/lib/storage/tournaments";

interface FullLeaderboardProps {
  tournament: Tournament;
  onClose?: () => void;
  embedded?: boolean;
}

export default function FullLeaderboard({ tournament, onClose, embedded = false }: FullLeaderboardProps) {
  const tableRef = useRef<HTMLDivElement>(null);
  const [exporting, setExporting] = useState(false);
  const leaderboard = getLeaderboard(tournament);
  const matches = tournament.matches || [];

  const exportPNG = async () => {
    if (!tableRef.current) return;
    setExporting(true);
    try {
      const { toPng } = await import("html-to-image");
      const dataUrl = await toPng(tableRef.current, {
        backgroundColor: "#0a0a0f",
        quality: 1,
        pixelRatio: 2,
      });
      const link = document.createElement("a");
      link.download = `${tournament.name}-leaderboard.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error("PNG export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  const exportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

      doc.setFillColor(10, 10, 15);
      doc.rect(0, 0, 297, 210, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text(tournament.name.toUpperCase(), 148.5, 18, { align: "center" });

      doc.setFontSize(10);
      doc.setTextColor(150, 150, 170);
      doc.text(`LEADERBOARD · ${leaderboard.length} TEAMS · ${matches.length} MATCHES`, 148.5, 26, { align: "center" });

      const startY = 35;
      const rowH = 7;

      doc.setFillColor(30, 30, 50);
      doc.rect(8, startY, 281, rowH, "F");
      doc.setTextColor(100, 150, 255);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text("RANK", 10, startY + 5);
      doc.text("SQUAD", 25, startY + 5);

      for (let i = 0; i < Math.min(matches.length, 12); i++) {
        doc.text(`M${i + 1}`, 65 + i * 11, startY + 5, { align: "center" });
      }
      doc.text("KILLS", 200, startY + 5, { align: "center" });
      doc.text("PLACE", 218, startY + 5, { align: "center" });
      doc.text("KILL", 236, startY + 5, { align: "center" });
      doc.text("TOTAL", 258, startY + 5, { align: "center" });

      leaderboard.slice(0, 20).forEach((entry, idx) => {
        const y = startY + rowH + idx * rowH;
        if (idx % 2 === 0) { doc.setFillColor(20, 20, 30); doc.rect(8, y, 281, rowH, "F"); }
        const isTop3 = idx < 3;
        if (isTop3) {
          const colors: [number,number,number][] = [[255,215,0],[192,192,192],[205,127,50]];
          doc.setTextColor(...colors[idx]);
        } else {
          doc.setTextColor(200, 200, 220);
        }
        doc.setFontSize(7);
        doc.setFont("helvetica", isTop3 ? "bold" : "normal");
        doc.text(`#${entry.rank}`, 10, y + 5);
        doc.text(entry.teamName.substring(0, 16), 25, y + 5);
        for (let i = 0; i < Math.min(matches.length, 12); i++) {
          const r = entry.matchResults?.[matches[i]?.id];
          doc.text(r ? String(r.totalPoints) : "-", 65 + i * 11, y + 5, { align: "center" });
        }
        doc.setTextColor(255, 150, 100);
        doc.text(String(entry.totalKills || 0), 200, y + 5, { align: "center" });
        doc.setTextColor(100, 200, 255);
        doc.text(String(entry.placementPoints || 0), 218, y + 5, { align: "center" });
        doc.text(String(entry.killPoints || 0), 236, y + 5, { align: "center" });
        doc.setTextColor(255, 255, 100);
        doc.setFont("helvetica", "bold");
        doc.text(String(entry.totalPoints), 258, y + 5, { align: "center" });
      });

      doc.setTextColor(80, 80, 100);
      doc.setFontSize(7);
      doc.text(`Generated by TournaOps · tournaops.com · ${new Date().toLocaleDateString()}`, 148.5, 205, { align: "center" });
      doc.save(`${tournament.name}-leaderboard.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  const getRankStyle = (rank: number) => {
    if (rank === 1) return "text-yellow-400 font-bold";
    if (rank === 2) return "text-gray-300 font-bold";
    if (rank === 3) return "text-amber-600 font-bold";
    return "text-gray-400";
  };

  const content = (
    <div ref={tableRef} className="p-6 bg-[#0a0a0f] rounded-xl">
      <div className="text-center mb-6">
        <div className="text-xs text-blue-500/60 font-mono uppercase tracking-widest mb-1">TournaOps · tournaops.com</div>
        <h2 className="text-2xl font-bold text-white">{tournament.name}</h2>
        <p className="text-gray-500 text-sm mt-1">{leaderboard.length} Squads · {matches.length} Matches</p>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-white/10">
              <th className="text-left py-3 px-3 text-gray-500 font-medium text-xs uppercase w-12">Rank</th>
              <th className="text-left py-3 px-3 text-gray-500 font-medium text-xs uppercase">Squad</th>
              {matches.slice(0, 12).map((m, i) => (
                <th key={m.id} className="text-center py-3 px-2 text-gray-600 font-medium text-xs w-10">M{i + 1}</th>
              ))}
              <th className="text-center py-3 px-3 text-gray-500 font-medium text-xs uppercase">Kills</th>
              <th className="text-center py-3 px-3 text-gray-500 font-medium text-xs uppercase">Place</th>
              <th className="text-center py-3 px-3 text-gray-500 font-medium text-xs uppercase">Kill Pts</th>
              <th className="text-center py-3 px-3 text-blue-400 font-bold text-xs uppercase">Total</th>
            </tr>
          </thead>
          <tbody>
            {leaderboard.map((entry) => (
              <tr key={entry.teamId} className="border-b border-white/5 hover:bg-white/3 transition-colors">
                <td className="py-2.5 px-3">
                  <span className={`font-mono text-sm ${getRankStyle(entry.rank)}`}>
                    {entry.rank === 1 ? "🥇" : entry.rank === 2 ? "🥈" : entry.rank === 3 ? "🥉" : `#${entry.rank}`}
                  </span>
                </td>
                <td className="py-2.5 px-3 text-white font-semibold">{entry.teamName}</td>
                {matches.slice(0, 12).map((m) => {
                  const r = entry.matchResults?.[m.id];
                  return (
                    <td key={m.id} className="py-2.5 px-2 text-center">
                      {r ? <span className="text-gray-300 font-mono text-xs">{r.totalPoints}</span> : <span className="text-gray-700 text-xs">—</span>}
                    </td>
                  );
                })}
                <td className="py-2.5 px-3 text-center text-orange-400 font-mono font-bold">{entry.totalKills || 0}</td>
                <td className="py-2.5 px-3 text-center text-blue-300 font-mono">{entry.placementPoints || 0}</td>
                <td className="py-2.5 px-3 text-center text-green-400 font-mono">{entry.killPoints || 0}</td>
                <td className="py-2.5 px-3 text-center">
                  <span className={`font-mono font-bold ${entry.rank <= 3 ? "text-yellow-400" : "text-white"}`}>{entry.totalPoints}</span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="mt-4 text-center text-xs text-gray-700 font-mono">
        Generated by TournaOps · tournaops.com · {new Date().toLocaleDateString()}
      </div>
    </div>
  );

  if (embedded) return content;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/80 backdrop-blur-sm overflow-y-auto py-8">
      <div className="w-full max-w-6xl mx-4">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold text-white">Full Leaderboard</h2>
          <div className="flex items-center gap-3">
            <button onClick={exportPNG} disabled={exporting} className="btn-secondary flex items-center gap-2 px-4 py-2">
              <Download className="w-4 h-4" />
              {exporting ? "Exporting..." : "Export PNG"}
            </button>
            <button onClick={exportPDF} disabled={exporting} className="btn-secondary flex items-center gap-2 px-4 py-2">
              <FileText className="w-4 h-4" />
              {exporting ? "Exporting..." : "Export PDF"}
            </button>
            {onClose && (
              <button onClick={onClose} className="p-2 rounded-lg hover:bg-white/10 text-gray-400 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            )}
          </div>
        </div>
        {content}
      </div>
    </div>
  );
}
